### ISSUE TITLE
Questions: Evaluating axe runner in pa11y

### ISSUE THREAD

**Issue by svattenky** [pa11y/pa11y-runner-axe#16]
Hi,
I was evaluating pa11y and I noticed it uses axe-runner as well. I had few questions

1. What standard does the axe runner run against? I noticed I got more errors with axe than with the default runner of pa11y
2. In the pa11y help it says ` -s, --standard <name>          the accessibility standard to use: Section508, WCAG2A, WCAG2AA (default), WCAG2AAA – only used by htmlcs runner` - Will the axe-runner have support soon to chose the standards?
3. In the pa11y help it also says `    -A, --add-rule <rule>          WCAG 2.0 rules to include, a repeatable value or separated by semi-colons – only used by htmlcs runner` - Same question will axe-runner have support soon to add custom rules?

**Comment by josebolos** [comment]
Hi @angelblade27 

Thanks for creating this issue! If my understanding is correct, [axe-core uses a mix of rules](https://github.com/dequelabs/axe-core/blob/v3.5.3/doc/rule-descriptions.md) that the axe team has picked based on a number of criteria that they consider important for their goals of having a comprehensive set of tests without offering false positives. In practice, this means that they use a mix of rules handpicked from WCAG 2.0, 2.1, and industry best practices.

As such, I don't think it would make much sense to try to force axe to do something that it doesn't do natively, but we of course would consider any contributions in that regard, assuming they can be made in a way that is consistent with the architecture of both pa11y and axe.

**Comment by svattenky** [comment]
Thanks, @josebolos . It looks like someone already committed it https://github.com/pa11y/pa11y-runner-axe/pull/14 and it just needs to be released in 1.x. Can someone release it?
