### ISSUE TITLE
How to know if the Axe runner is working?

### ISSUE THREAD

**Issue by alberto56** [pa11y/pa11y-runner-axe#3]
I am getting the same output using the axe runner (as per the instructions) as when I am not using it. Is there any way I can tell, from the output, that axe runner is actually being used (vs the default codesniffer runner)?

**Comment by hollsk** [comment]
Hi @alberto56 - thanks for using Pa11y! 

The output gives you a link to the Axe documentation (dequeuniversity.com) for each of its rules, so you'll see something like this:

```
 • Error: Elements should not have tabindex greater than zero (https://dequeuniversity.com/rules/axe/3.0/tabindex?application=axeAPI)
   ├── tabindex
   ├── #alert-box-message > a
   └── <a href="/privacy.html" class="banner-policy-link" tabindex="1">Privacy Policy</a>
```

If you don't see a link to that site, then the axe runner isn't actually being used.

**Comment by alberto56** [comment]
Thanks, that answers my question!
